#!/bin/bash

set -euxo pipefail

if git show-ref --verify --quiet refs/heads/aaa; then
    git branch -D aaa
fi
git checkout -b aaa
echo $(uuidgen) > bruh
git add .
git commit -m "first commit"
./expand-all-packfiles
git push -u origin aaa
git push origin --delete aaa
git checkout master